#!/usr/bin/env bash
# prints a string 10 times using while loop 

i=0

while [ "$i" -lt 10 ]; do

#using if to change sentence
if [ $i -eq 8 ]; then 
	echo "Hi"
else
	echo "Best School"
fi
((i++))
done
